version: "3"

volumes:
  db-data:
    external: false

services:
  app:
    build: .
    command: |
      bash -c "rm -f tmp/pids/server.pid \
      && bundle exec puma -C config/puma.rb \
      & bundle exec guard -i"
    environment:
      - RAILS_ENV=development
      - PORT=3000
      - DISABLE_DATABASE_ENVIRONMENT_CHECK=1
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    working_dir: /myapp
    volumes:
      - .:/myapp
    ports:
      - 3000:3000
      - 35729:35729
    depends_on:
      - db

  db:
    image: postgres:10.3-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
