default: &default
  adapter: postgresql
  encoding: utf8
  host: db
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  pool: 5
  timeout: 5000
  variables:
    tcp_keepalives_idle: 60
    tcp_keepalives_interval: 60
    tcp_keepalives_count: 100

development:
  <<: *default
  database: railsgoat_dev

test:
  <<: *default
  database: railsgoat_test

production:
  <<: *default
  database: railsgoat_production
